Blog/config/routes.rb
Rails.application.routes.draw do

  get 'login' => 'sessions#new'
  post '/' => 'posts#create'
  post 'login' => 'sessions#create'
  get 'products' => 'products#index'
  get 'developers' => 'developers#index'
  get 'about_us' => 'about_us#index'
  delete 'logout' => 'sessions#destroy'
  delete 'delete_post' => 'posts#destroy'
  root 'posts#index'
  resources :posts

end

Blog/app/models/post.rb
class Post < ActiveRecord::Base
validates :title, :content, :presence => true
validates :title , :uniqueness => true
end

Blog/app/models/user.rb
class User < ActiveRecord::Base
has_secure_password
validates :uname , :password , :fname , :lname , :email ,:presence => true
end

Blog/app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
def index

end

end

Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

Blog/app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
def index

end

end

Blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
      @post = Post.all
      @user = current_user
  end

  def update
      @post = Post.find(params[:id])  
      if @post.update_attributes(post_params)
      redirect_to '/'
    else
      render 'edit'
    end
  end

  def edit
      @post = Post.find(params[:id])
  end

  def create
      Post.create(title: params[:create][:title],
        content: params[:create][:content],
        user_id: current_user.id)
      redirect_to '/'
  end

  def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to '/' , :notice => "Post deleted"
  end

end

def post_params
      params.require(:post).permit(:title, :content)
end

Blog/app/controllers/products_controller.rb
class ProductsController < ApplicationController

def index

end

end

Blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(uname: params[:session][:uname])
  	if(user&&user.authenticate(params[:session][:password]))
  		log_in(user)
  		redirect_to '/' , :flash => {:notice =>"Welcome #{user.uname}"}
  	else
  		redirect_to '/' , :flash => {:error => 'Invalid email/password combination'}
  	end
  end

  def destroy
    log_out
    redirect_to '/'
  end
end

Blog/app/controllers/users_controller.rb
class UsersController < ApplicationController

end

Blog/app/helpers/about_us_helper.rb
module AboutUsHelper
end

Blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Blog/app/helpers/developers_helper.rb
module DevelopersHelper
end

Blog/app/helpers/posts_helper.rb
module PostsHelper

  def get_name(id)
     pid = Post.find(id).user_id
     User.all.find(pid).uname
  end


end

Blog/app/helpers/products_helper.rb
module ProductsHelper
end

Blog/app/helpers/sessions_helper.rb
module SessionsHelper

def log_in(user)
   session[:user_id] = user.id
end

 def current_user
    @current_user =@current_user || User.find_by(id: session[:user_id])
 end
def log_out
session.delete(:user_id)
current_user = nil
end

def logged_in?
 !current_user.nil?
end

end

Blog/app/helpers/users_helper.rb
module UsersHelper
end

Blog/app/views/about_us/index.html.erb
<!DOCTYPE html>

<html>
<head>
     <%= stylesheet_link_tag "main" %>
   <%= stylesheet_link_tag "nav" %>
   <%= stylesheet_link_tag "login" %>
  <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <script src="script.js"></script>
    <script src='http://codepen.io/assets/libs/fullpage/jquery.js'></script>
  <script src="login.js"></script>
</head>

  <body> 
     <div class = "logo">
<%=link_to image_tag("logo.jpg", :border => 0 ,  :class => 'img'), root_path%>

<%if !logged_in?%>
<span href="#" class="button" id="toggle-login" onclick="toggle_visibility('login');">Log In</span>
<div class="login" id="login" >
  <div class="titulo">Staff Login</div>
      <%=form_for :session , url:login_path do |f|%>
      <%= f.text_field :uname ,:placeholder => "User name" , class: 'text2' %>
      <%= f.password_field :password , :placeholder => "Pasword" , class: 'text2' %>
      <%= f.submit 'Log Me In' , class: 'enviar' %>
      <%end%>
      <%else%>
  <span  class="button" id="toggle-login"><%= link_to "Logout" , logout_path ,  method: :delete , class: 'logout'%></span>
    <%end%>
</div>
</div>


<div id='cssmenu'>
<ul>
   <li><%=link_to "Home",root_path%><span></span></li>
   <li><%=link_to "Products" ,products_path %><span></span></a></li>
   <li><%=link_to 'Developers' , developers_path %><span></span></li>
   <li class= 'active' class='last'><%=link_to 'About us',about_us_path%><span></span></li>
</ul>
</div>
<div class = "mainPage">
  <pre>
    <%= image_tag 'logo_big.png', id:'logobig'%>
    </pre>
  <h3 id="info">WonderCode is a startup software company founded in 2015 while developing a project accourding to the Software Engineering course in the German
    University in Cairo. WonderCode provieds brilliant software solutions with outstanding stability and high potentials.
  </h3>
  </div>

</body>
  <div id="divfooter">
    <pre id="footer">All Copyrights Reserved 2015</pre>
  </div>
</div>
</html>

Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WondercodeBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Blog/app/views/posts/edit.html.erb
<html>
	<head>
   <%= stylesheet_link_tag "main" %>
   <%= stylesheet_link_tag "nav" %>
   <%= stylesheet_link_tag "login" %>
  <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <script src="script.js"></script>
    <script src='http://codepen.io/assets/libs/fullpage/jquery.js'></script>
  <script src="login.js"></script>
</head>

	<body> 
     <div class = "logo">
<%=link_to image_tag("logo.jpg", :border => 0 ,  :class => 'img'), root_path %>

<%if !logged_in?%>
<span href="#" class="button" id="toggle-login" onclick="toggle_visibility('login');">Log In</span>
<div class="login" id="login" >
  <div class="titulo">Staff Login</div>
      <%=form_for :session , url:login_path do |f|%>
      <%= f.text_field :uname ,:placeholder => "User name" , class: 'text2' %>
      <%= f.password_field :password , :placeholder => "Pasword" , class: 'text2' %>
      <%= f.submit 'Log Me In' , class: 'enviar' %>
      <%end%>
      <%else%>

  <span  class="button" id="toggle-login"><%= link_to "Logout" , logout_path ,  method: :delete , class: 'logout'%></span>
    <%end%>
</div>
</div>


<div id='cssmenu'>
<ul>
   <li class='active'>
    <%=link_to "Home",root_path%><span></span></li>
   <li><%=link_to "Products" ,products_path %><span></span></li>
   <li><%=link_to 'Developers' , developers_path %><span></span></li>
   <li class='last'><%=link_to 'About us',about_us_path%><span></span></li>
</ul>
</div>
<div class = "mainPage"><pre>
  
</pre>

	<%= form_for @post do |f| %>
	<%= f.text_field :title , :placeholder => "Title" , class: 'msgE'%>
	<%= f.text_area :content , :placeholder => "Content" , class: 'msgC'%>
	<%= f.submit 'Save' , class: 'button1'%>
	<%end%>


</div>







</body>
  <div id="divfooter">
    <pre id="footer">All Copyrights Reserved 2015</pre>
  </div>
</html>

Blog/app/views/posts/index.html.erb
<html>
	<head>
   <%= stylesheet_link_tag "main" %>
   <%= stylesheet_link_tag "nav" %>
   <%= stylesheet_link_tag "login" %>
  <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <script src="script.js"></script>
    <script src='http://codepen.io/assets/libs/fullpage/jquery.js'></script>
  <script src="login.js"></script>
</head>

	<body> 
     <div class = "logo">
<%=link_to image_tag("logo.jpg", :border => 0 ,  :class => 'img'), root_path %>

<%if !logged_in?%>
<span href="#" class="button" id="toggle-login" onclick="toggle_visibility('login');">Log In</span>
<div class="login" id="login" >
  <div class="titulo">Staff Login</div>
      <%=form_for :session , url:login_path do |f|%>
      <%= f.text_field :uname ,:placeholder => "User name" , class: 'text2' %>
      <%= f.password_field :password , :placeholder => "Pasword" , class: 'text2' %>
      <%= f.submit 'Log Me In' , class: 'enviar' %>
      <%end%>
      <%else%>

  <span  class="button" id="toggle-login"><%= link_to "Logout" , logout_path ,  method: :delete , class: 'logout'%></span>
    <%end%>
</div>
</div>


<div id='cssmenu'>
<ul>
   <li class='active'>
    <%=link_to "Home",root_path%><span></span></li>
   <li><%=link_to "Products" ,products_path %><span></span></li>
   <li><%=link_to 'Developers' , developers_path %><span></span></li>
   <li class='last'><%=link_to 'About us',about_us_path%><span></span></li>
</ul>
</div>
<div class = "mainPage"><pre>
  
</pre>
<%if @post.empty? && logged_in?%>
<%= form_for :create do |f| %>

        <%= f.text_field :title , :placeholder => "Write Title Here.." , class: 'msgE'%>
        <br>
        <%= f.text_area :content , :placeholder => "Write Post Here..." , class: 'msgC'%>
        <br>
        <br>
    <%= f.submit 'Post' , class: 'postB'%>
        <%end%>
<%else%>

<%@post.each do |p|%>
 <div class="comment">
        <h5> <%= p.title %>: </h5>
         <br>
          <%=p.content %>
          <br>
          <br>
          <br>
          </div>
          <% %>
              <h2>  Added By <%= get_name(p)%> </h2> 
        <br>
         	  
                 
	   <% if logged_in? %>
              <%= button_to "Delete Post" ,p, method: :delete , class: 'button2' %>
         <%= button_to "Edit Post" ,edit_post_path(p) , method: :get , class: 'button1'%>

               <%end%>
               <%end%>

             <% if logged_in? %>
          <div>
        <%= form_for :create do |f| %>

        <%= f.text_field :title , :placeholder => "Write Title Here.." , class: 'msg'%>
        <br>
        <%= f.text_area :content , :placeholder => "Write Post Here..." , class: 'msgC'%>
        <br>
        <br>
		<%= f.submit 'Post' , class: 'postB'%>
        <%end%>
		</div>
       <%end%>
       <%end%>
        </div>
     </div>
     </div>
</div>

	</body>
    <div id="divfooter">
    <pre id="footer">All Copyrights Reserved 2015</pre>
  </div>
</html>

Blog/app/views/products/index.html.erb
<!DOCTYPE html>

<html>
<head>
     <%= stylesheet_link_tag "main" %>
   <%= stylesheet_link_tag "nav" %>
   <%= stylesheet_link_tag "login" %>
  <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <script src="script.js"></script>
    <script src='http://codepen.io/assets/libs/fullpage/jquery.js'></script>
  <script src="login.js"></script>
</head>

  <body> 
     <div class = "logo">
<%=link_to image_tag("logo.jpg", :border => 0 ,  :class => 'img'), root_path%>

<%if !logged_in?%>
<span href="#" class="button" id="toggle-login" onclick="toggle_visibility('login');">Log In</span>
<div class="login" id="login" >
  <div class="titulo">Staff Login</div>
      <%=form_for :session , url:login_path do |f|%>
      <%= f.text_field :uname ,:placeholder => "User name" , class: 'text2' %>
      <%= f.password_field :password , :placeholder => "Pasword" , class: 'text2' %>
      <%= f.submit 'Log Me In' , class: 'enviar' %>
      <%end%>
      <%else%>
  <span  class="button" id="toggle-login"><%= link_to "Logout" , logout_path ,  method: :delete , class: 'logout'%></span>
    <%end%>
</div>
</div>



<div id='cssmenu'>
<ul>
   <li ><%=link_to "Home",root_path%><span></span></li>
   <li class='active'><%=link_to "Products" ,products_path %><span></span></li>
   <li><%=link_to 'Developers' , developers_path %><span></span></li>
   <li class='last'><%=link_to 'About us',about_us_path%><span></span></li>
</ul>
</div>
<div class = "mainPage"><pre>
  <h1 id="productT">Working On</h1>
  <h6 id="products"> KNELLEN </h6>

</pre></div>
</body>
  <div id="divfooter">
    <pre id="footer">All Copyrights Reserved 2015</pre>
  </div>
</html>